version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtest
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@desarrollo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "9000:80"
    depends_on:
      - postgres
volumes:
  pgdata:
