version: "3.6"

services:
  postgres:
    #image: postgres:13 #version Especifica
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtest
      - PGDATA= /var/lib/postgres/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@desarrollo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "9000:80"
    depends_on:
      - postgres
volumes:
  pgdata:
